title: MY WRITING
email: your-email@example.com
description: >-
  des
baseurl: ""
url: "https://psswordprotectd.com"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 10
paginate_path: /page:num/
permalink: pretty  # <- Fixed line
timezone: America/Chicago